import type { Applicant } from "../../src/types";

export const DEFAULT_APPLICANT: Applicant = {
  scheme_country: "JAPAN",
  personal: {
    country_of_birth: "Vietnam",
    date_of_birth: "2 December, 2000",
    family_name: "Ha Tinh",
    gender: "Male",
    given_name_1: "Oi",
    given_name_2: "",
    given_name_3: "",
    other_names: "",
    other_title: "",
    title: "Mr",
  },
  address: {
    city: "Ha Noi",
    country: "Vietnam",
    postal_code: "100000",
    province: "Ha Noi",
    street_name: "Xuan Dinh",
    street_number: "789",
    suburb: "Bac Tu Liem",
  },
  contact: {
    communication_method: "Email",
    email: "quangnv.ftuforum@gmail.com",
    fax: "",
    has_agent: "No",
    has_credit_card: "Yes",
    phone_daytime: "0942361202",
    phone_mobile: "+84942361202",
    phone_night: "",
  },
  identification: {
    id_expiry_date: "8 August, 2030",
    id_issue_date: "4 August, 2026",
    id_type: "National ID",
    passport_expiry: "28 August, 2031",
    passport_number: "E08977777",
  },
  occupation: {
    industry_search: "",
    occupation_search: "",
  },
  health: {
    active_tb: "No",
    cancer: "No",
    disability: "No",
    heart_disease: "No",
    hospitalisation: "No",
    medical_details: "",
    pregnancy: "No",
    renal_dialysis: "No",
    residential_care: "No",
    tb_risk: "Yes",
  },
  character: {
    charged: "No",
    convicted: "No",
    deported: "No",
    details: "",
    excluded: "No",
    imprisonment_12_months: "No",
    imprisonment_5_years: "No",
    removed: "No",
    under_investigation: "No",
  },
  whs: {
    previous_whs_visa: "No",
    sufficient_funds_holiday: "Yes",
    travel_date: "20 November, 2026",
    been_to_nz: "No",
    been_to_nz_when: "",
    sufficient_funds_onward_ticket: "Yes",
    meet_scheme_requirements: "Yes",
  },
  payment: {
    payer_name: "Vu Quang Nguyen",
  },
};
